### ISSUE TITLE
cc2538 not displaying

### ISSUE THREAD

**Issue by latapata** [thingsquare/hardware#1]
Hello All,

I have powered up the cc2530, connected the Router as instructed in the webpage. By using the Ti RF programmer I have also burned the program into the board. While I switch it on it is not displaying anything. The power configurations are correct. Please let me know if somebody has faced the same problem and the soultions to it.

**Comment by adamdunkels** [comment]
The demo runs on the [TI CC2538](http://www.ti.com/product/cc2538) which is a (very) different chip from the [TI CC2530](http://www.ti.com/product/cc2530), even if the names are similar.

The demo does not run on the CC2530.

**Comment by latapata** [comment]
Hello 

Thanks a lot for the reply. 

I did a mistake it is a TI CC2538 board and not TI CC2530. To test whether the hardware is working properly, i burned other code (kit code) into it and it is working properly but as a router it is not working. 

I have another question what if the ethernet is not connected to the CC2538 board will it display anything still ?
