### ISSUE TITLE
Openmote Bootloader Backdoor Disabled

### ISSUE THREAD

**Issue by pablocorbalan** [thingsquare/hardware#5]
Hi,

I tried yesterday the new released beta with the OpenMote Hardware and if I am not wrong, the Bootloader Backdoor is disabled in the binary provided. As a consequence, if you flash the OpenMote with that binary, it won't be possible to reprogram again the mote with the cc2538-bsl tool and you will need to use a JTAG programmer. 

I think you may want to enable the Bootloader Backdoor and recompile the binary.

**Comment by adamdunkels** [comment]
Great feedback, will look into it - thanks!

**Comment by adamdunkels** [comment]
The backdoor should be enabled now btw.
